### ISSUE TITLE
list of abbreviations includes items not referenced in document

### ISSUE THREAD

**Issue by sagerx-greghather** [yonicd/glossaries#1]
abbreviations in glossary.yml appear even when they are not referenced in the document

**Comment by yonicd** [comment]
for this you need to use chunk caching and the new build of this package https://github.com/yonicd/glossaries/commit/d72230de063f80a67535b37ef22ba35b7db29c31

at the end of the document, put this chunk

````
```{r definitions, echo=FALSE, cache=TRUE, cache.rebuild = TRUE}
definition_tbl <- glossary_to_flextable(used_entries('definition'))
```
```{r acronyms, echo=FALSE, cache=TRUE, cache.rebuild = TRUE}
acronym_tbl <- glossary_to_flextable(used_entries('acronym'))
```
````

that creates the table with only the used definitions and a table for the used acronyms

then at the place where you want the actual table to show you put these chunks

````
## Definitions

```{r, echo=FALSE}
knitr::load_cache('definitions', 'definition_tbl')
```

## Acronyms

```{r, echo=FALSE}
knitr::load_cache('acronyms', 'acronym_tbl')
```
````

**Comment by sagerx-greghather** [comment]
Thanks, Yoni.  The tables didn't show up in the report when I tried it.  We can sort this out next time we chat.

**Comment by yonicd** [comment]
You need to knit twice
